### ISSUE TITLE
Can't able to setup material-components-android-compose-theme-adapter

### ISSUE THREAD

**Issue by aiyu-ayaan** [material-components/material-components-android-compose-theme-adapter#100]
## Dependency
```
dependencies {
   implementation "com.google.android.material:compose-theme-adapter-3:1.0.22"
}
```

## Error 
``` 
Failed to resolve: material-components-android-compose-theme-adapter:core:unspecified
Show in Project Structure dialog
Affected Modules: bitapp
```

**Comment by ricknout** [comment]
There was a delay between the GitHub release and the artifacts becoming available on gMaven. They should be available now:
* https://maven.google.com/web/index.html#com.google.android.material:compose-theme-adapter:1.1.22
* https://maven.google.com/web/index.html#com.google.android.material:compose-theme-adapter-3:1.0.22

**Comment by ricknout** [comment]
This should now be fixed in the latest releases:
* Material: https://github.com/material-components/material-components-android-compose-theme-adapter/releases/tag/material-v1.2.0
* Material 3: https://github.com/material-components/material-components-android-compose-theme-adapter/releases/tag/material3-v1.1.0
* Core: https://github.com/material-components/material-components-android-compose-theme-adapter/releases/tag/core-v1.0.0

**Comment by aiyu-ayaan** [comment]
Ohk @ricknout i will check it out
