### ISSUE TITLE
Including the library in a dynamic feature module changes typography themes elements

### ISSUE THREAD

**Issue by fbarthelery** [material-components/material-components-android-compose-theme-adapter#20]
I got a weird issue when I tried to include the library in a dynamic feature module. I don't know what is happening exactly but this seems to modify some theme attributes used in the regular view system. 

Here is a link to a minimal sample reproduction
https://github.com/fbarthelery/Bug-material-components-android-compose-theme-adapter

#### Without compose-theme-adapter dependency

<img src="https://github.com/fbarthelery/Bug-material-components-android-compose-theme-adapter/raw/main/screenshots/without.png" height="500"/>

#### With compose-theme-adapter dependency

<img src="https://github.com/fbarthelery/Bug-material-components-android-compose-theme-adapter/raw/main/screenshots/with.png" height="500"/>

**Comment by chrisbanes** [comment]
First of all, this isn't a library issue. You're not invoking any MDC Adapter code (or even Compose code for that matter) so there's no way it can alter the theme. This library also doesn't modify the theme in any way.

This looks to me like a Gradle transitive dependency issue. This library depends on MDC `1.1.0`, to _not_ force consumers to upgrade if they don't want/need to. I'd try forcing the MDC version you want using by [overriding the transitive dependency version](https://docs.gradle.org/current/userguide/dependency_downgrade_and_exclude.html):

```
implementation 'com.google.android.material:material:1.2.1!!'
```

This should happen automatically, since:
> Gradle resolves any dependency version conflicts by selecting the latest version found in the dependency graph

But maybe being a feature module is how messing with it some how.

**Comment by chrisbanes** [comment]
Looked more into this. It's not a transitive dependency issue, the MDC dependency gets correctly upgraded to: `com.google.android.material:material:1.1.0 -> 1.2.1 (*)`.

This looks to me like a feature module issue. If I add `implementation 'com.google.android.material:compose-theme-adapter:1.0.0-alpha02'` to the app module (as well as the feature module), it all works correctly. I'm guessing that the resource IDs are somehow not correctly resolved when the dependency is only the feature module. Not much we can do in the library though.

**Comment by chrisbanes** [comment]
Adding @keyboardsurfer @wojtek-kalicinski

**Comment by keyboardsurfer** [comment]
I can reproduce the issue. For now, replacing `?textAppearanceHeadline3` with `@style/TextAppearance.MaterialComponents.Headline3` is a feasible workaround.
We'll have to look into this more in depth to get it fully resolved though.

**Comment by fbarthelery** [comment]
I agree this is not a library issue but I had no clue where to start.

I'm happy to fill an issue in the correct component so this can be followed up properly.
